
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/blogs/654c1404d4b40776b4d654b2

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZ3VlbSIsImlkIjoiNjU0ZWM3NWRlMDUxMTYwYjZlNDVkYTYyIiwiaWF0IjoxNjk5NjY0Nzg5fQ.wWVGTVUrlPRx9Vzf-DGyJkuyWdbYBO1VMEalVg-IeR8

{
    "title":"teste Authorization",
    "author": "testando",
    "url": "test.authorization.com",
    "likes": 99
}

###
DELETE http://localhost:3003/api/blogs/654c23efcd619f22b0868137
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFsZ3VlbSIsImlkIjoiNjU0ZWM3NWRlMDUxMTYwYjZlNDVkYTYyIiwiaWF0IjoxNjk5NjY0Nzg5fQ.wWVGTVUrlPRx9Vzf-DGyJkuyWdbYBO1VMEalVg-IeR8