GET http://localhost:3003/api/users

###
GET http://localhost:3003/api/users/654bf7f2978b9f620b46a07c

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "name":"nameRequest",
    "username": "usernameRequest",
    "password": "secreto"
}

###
DELETE http://localhost:3003/api/users/6540262cdff794894d0d5410
