###
GET https://phonelist.fly.dev/api/persons

###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/650130953af189e33f6896b2

###
DELETE http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/98765

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "new person",
    "numbers": ["12345678", "12-12345678", "123-12345678"]
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "numbers": ["040-12345678"]
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "new person"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "p",
    "numbers": ["456-12345678"]
}

###
PUT http://localhost:3001/api/persons/650130953af189e33f6896b2
content-type: application/json

{
    "name": "Updated Name",
    "numbers": ["1234567"]
}

###
PUT http://localhost:3001/api/persons/650130953af189e33f6896b2
content-type: application/json

{
    "name": "New Person",
    "numbers": ["87654321", "09-87654321", "009-87654321"]
}

###
PUT http://localhost:3001/api/persons/650130953af189e33f6896b2
content-type: application/json

{
    "name": "New Person",
    "numbers": ["87654321", "09-87654321", "009-87654321","12345678"]
}

###
PUT http://localhost:3001/api/persons/650130953af189e33f6896b2
content-type: application/json

{
    "name": "a",
    "numbers": ["12-1234567"]
}

###
PUT http://localhost:3001/api/persons/650130953af189e33f6896b2
content-type: application/json

{
    "name": "New Person",
}