###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/api/persons/98765

###
DELETE http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/98765

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "new person",
    "numbers": ["040-123456"]
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
  # "name": "new person",
    "number": ["040-123456"]
}

###
GET https://phonelist.fly.dev/api/persons